// Generated by Phaser Editor v1.2.1

/**
 * startCanvas.
 * @param {Phaser.Game} aGame The game.
 * @param {Phaser.Group} aParent The parent group. If not given the game world will be used instead.
 */
function startCanvas(aGame, aParent) {
	Phaser.Group.call(this, aGame, aParent);

	/* --- pre-init-begin --- */

	// you can insert code here

	/* --- pre-init-end --- */

	this.game.add.sprite(0, 0, 'startBackground', null, this);

	var optionsButton = this.game.add.button(1500, 100, 'startAtlas', null, this, null, 'options', null, null, this);
	optionsButton.anchor.setTo(0.5, 0.5);

	var startButton = this.game.add.button(400, 100, 'startAtlas', startGame, this, null, 'start', null, null, this);
	startButton.anchor.setTo(0.5, 0.5);

	 // public fields

	this.fOptionsButton = optionsButton;
	this.fStartButton = startButton;

	/* --- post-init-begin --- */

	startButton.onInputOver.add(buttonScale, {button : this.fStartButton, scale: 1.25});
	startButton.onInputOut.add(buttonScale, {button : this.fStartButton, scale: 1});
	optionsButton.onInputOver.add(buttonScale, {button : this.fOptionsButton, scale: 1.25});
	optionsButton.onInputOut.add(buttonScale, {button : this.fOptionsButton, scale: 1});

	/* --- post-init-end --- */
}

/** @type Phaser.Group */
var startCanvas_proto = Object.create(Phaser.Group.prototype);
startCanvas.prototype = startCanvas_proto;
startCanvas.prototype.constructor = Phaser.Group;

/* --- end generated code --- */


/*
 * Starts the game when clicking the start button.
 */
function startGame() {
	this.game.state.start("Alarm");
	
}

