// Generated by Phaser Editor v1.2.1

/**
 * bedroomCanvas.
 * @param {Phaser.Game} aGame The game.
 * @param {Phaser.Group} aParent The parent group. If not given the game world will be used instead.
 */
function bedroomCanvas(aGame, aParent) {
	Phaser.Group.call(this, aGame, aParent);

	/* --- pre-init-begin --- */

	this.goToLivingroom = function() {
		this.game.state.start("GameOver");
	};

	/* --- pre-init-end --- */

	this.game.add.sprite(0, 0, 'bedroom_bg', null, this);

	var door = this.game.add.button(1775, 409, 'door', this.goToLivingroom, this, null, 0, null, null, this);
	door.anchor.setTo(0.5, 0.5);
	door.animations.add('open', [0, 1, 2, 3], 6, false);
	door.animations.add('close', [3, 2, 1, 0], 6, false);

	 // public fields

	this.fDoor = door;

	/* --- post-init-begin --- */
	
	
	

	/* --- post-init-end --- */
}

/** @type Phaser.Group */
var bedroomCanvas_proto = Object.create(Phaser.Group.prototype);
bedroomCanvas.prototype = bedroomCanvas_proto;
bedroomCanvas.prototype.constructor = Phaser.Group;

/* --- end generated code --- */



