// Generated by Phaser Editor v1.2.1

/**
 * BusStopCanvas.
 * @param {Phaser.Game} aGame The game.
 * @param {Phaser.Group} aParent The parent group. If not given the game world will be used instead.
 */
function BusStopCanvas(aGame, aParent) {
	Phaser.Group.call(this, aGame, aParent);

	/* --- pre-init-begin --- */

	// you can insert code here

	/* --- pre-init-end --- */

	this.game.add.sprite(0, 0, 'busentrance_bg', null, this);

	var toll = this.game.add.button(1440, 832, 'homeAtlas', null, this, null, 'toll_1', null, null, this);
	toll.anchor.setTo(0.5, 0.5);

	var leftDoor = this.game.add.group(this);

	var busWindow1 = this.game.add.tileSprite(0, 0, 100, 100, 'homeAtlas', 'busWindow', leftDoor);
	busWindow1.scale.setTo(9.659352808001968, 10.880704367494536);

	var busWindowFrame1 = this.game.add.tileSprite(936, -2, 25, 25, 'homeAtlas', 'busWindowFrame', leftDoor);
	busWindowFrame1.scale.setTo(1.0, 43.439972207727806);

	var rightDoor = this.game.add.group(this);

	var busWindow = this.game.add.tileSprite(960, 0, 100, 100, 'homeAtlas', 'busWindow', rightDoor);
	busWindow.scale.setTo(9.659352808001968, 10.880704367494536);

	var busWindowFrame = this.game.add.tileSprite(960, 0, 25, 25, 'homeAtlas', 'busWindowFrame', rightDoor);
	busWindowFrame.scale.setTo(1.0, 43.439972207727806);

	var busEdge2 = this.game.add.tileSprite(1730, -1, 25, 25, 'homeAtlas', 'busWindowFrame', this);
	busEdge2.scale.setTo(8.487998341797368, 43.620207279593714);

	var busEdge1 = this.game.add.tileSprite(-17, -5, 25, 25, 'homeAtlas', 'busWindowFrame', this);
	busEdge1.scale.setTo(8.487998341797368, 43.620207279593714);

	 // public fields

	this.fToll = toll;

	/* --- post-init-begin --- */
	//open the bus doors
	tween = this.game.add.tween(leftDoor).to( { x : -(this.game.width / 2) },
			3000, Phaser.Easing.Cubic.InOut, true);
	tween = this.game.add.tween(rightDoor).to( { x :this.game.width / 2},
			3000, Phaser.Easing.Cubic.InOut, true);
	
	this.fToll.onInputOver.add(buttonScale, {button : this.fToll, scale : 1.1});
	
	this.fToll.onInputOut.add(buttonScale, {button : this.fToll, scale : 1});
	
	

	/* --- post-init-end --- */
}

/** @type Phaser.Group */
var BusStopCanvas_proto = Object.create(Phaser.Group.prototype);
BusStopCanvas.prototype = BusStopCanvas_proto;
BusStopCanvas.prototype.constructor = Phaser.Group;

/* --- end generated code --- */

// you can insert code here

