// Generated by Phaser Editor v1.2.1

/**
 * KitchenCanvas.
 * @param {Phaser.Game} aGame The game.
 * @param {Phaser.Group} aParent The parent group. If not given the game world will be used instead.
 */
function KitchenCanvas(aGame, aParent) {
	Phaser.Group.call(this, aGame, aParent);

	/* --- pre-init-begin --- */

	// you can insert code here

	/* --- pre-init-end --- */

	this.game.add.sprite(0, 0, 'kitchen_bg', null, this);

	var kitchen_dishes = this.game.add.sprite(1030, 378, 'homeAtlas', 'kitchen_dishes', this);
	kitchen_dishes.scale.setTo(0.4442752627926752, 0.5396607959482412);

	var fridge = this.game.add.button(1442, 104, 'fridge', null, this, null, 0, null, null, this);
	fridge.animations.add('open', [0, 1, 2, 4], 6, false);
	fridge.animations.add('close', [4, 2, 1, 0], 6, false);

	var hallwayDoor = this.game.add.button(42, -42, 'bedroomDoor', null, this, null, 0, null, null, this);
	hallwayDoor.scale.setTo(1.1258682644930587, 1.2585629919047612);
	hallwayDoor.animations.add('open', [0, 1, 2, 3], 6, false);
	hallwayDoor.animations.add('close', [3, 2, 1, 0], 6, false);

	 // public fields

	this.fFridge = fridge;
	this.fHallwayDoor = hallwayDoor;

	/* --- post-init-begin --- */

	// you can insert code here

	/* --- post-init-end --- */
}

/** @type Phaser.Group */
var KitchenCanvas_proto = Object.create(Phaser.Group.prototype);
KitchenCanvas.prototype = KitchenCanvas_proto;
KitchenCanvas.prototype.constructor = Phaser.Group;

/* --- end generated code --- */

// you can insert code here

