// Generated by Phaser Editor v1.2.1

/**
 * alarmCanvas.
 * @param {Phaser.Game} aGame The game.
 * @param {Phaser.Group} aParent The parent group. If not given the game world will be used instead.
 */
function alarmCanvas(aGame, aParent) {
	Phaser.Group.call(this, aGame, aParent);

	/* --- pre-init-begin --- */

	// you can insert code here

	/* --- pre-init-end --- */

	this.game.add.sprite(0, 0, 'alarm_bg', null, this);


	/* --- post-init-begin --- */

	var style = { font: "bold 550px LCD", fill: "#f00"};

    //  The Text is positioned at 0, 100
    this.text = this.game.add.text(420, 250, "7:00", style);

	/* --- post-init-end --- */
}

/** @type Phaser.Group */
var alarmCanvas_proto = Object.create(Phaser.Group.prototype);
alarmCanvas.prototype = alarmCanvas_proto;
alarmCanvas.prototype.constructor = Phaser.Group;

/* --- end generated code --- */

// you can insert code here

