// Generated by Phaser Editor v1.2.1

/**
 * GameOverCanvas.
 * @param {Phaser.Game} aGame The game.
 * @param {Phaser.Group} aParent The parent group. If not given the game world will be used instead.
 */
function GameOverCanvas(aGame, aParent) {
	Phaser.Group.call(this, aGame, aParent);

	/* --- pre-init-begin --- */

	// you can insert code here

	/* --- pre-init-end --- */

	this.game.add.sprite(0, 0, 'gameOverBackground', null, this);

	var restartButton = this.game.add.button(448, 896, 'startAtlas', restartGame, this, null, 'restartButton', null, null, this);
	restartButton.anchor.setTo(0.5, 0.5);

	var learnButton = this.game.add.button(1472, 896, 'startAtlas', null, this, null, 'learnButton', null, null, this);
	learnButton.anchor.setTo(0.5, 0.5);

	 // public fields

	this.fRestartButton = restartButton;
	this.fLearnButton = learnButton;

	/* --- post-init-begin --- */

	restartButton.onInputOver.add(restartHover, this);
	restartButton.onInputOut.add(restartOut, this);
	learnButton.onInputOver.add(learnHover, this);
	learnButton.onInputOut.add(learnOut, this);


	/* --- post-init-end --- */
}

/** @type Phaser.Group */
var GameOverCanvas_proto = Object.create(Phaser.Group.prototype);
GameOverCanvas.prototype = GameOverCanvas_proto;
GameOverCanvas.prototype.constructor = Phaser.Group;

/* --- end generated code --- */

function restartHover() {
	this.fRestartButton.scale.setTo(1.25, 1.25);
}

/*
 * Resets the start button after leaving it
 */
function restartOut() {
	this.fRestartButton.scale.setTo(1, 1);	
}

/*
 * Handles Hovering over the Options Button
 */
function learnHover() {
	this.fLearnButton.scale.setTo(1.25, 1.25);
}

/*
 * Resets the options button after leaving it
 */
function learnOut() {
	this.fLearnButton.scale.setTo(1, 1);	
}

/*
 * Starts the game when clicking the start button.
 */
function restartGame() {
	this.game.state.start("Preload");
}

