// Generated by Phaser Editor v1.2.1

/**
 * GameOverCanvas.
 * @param {Phaser.Game} aGame The game.
 * @param {Phaser.Group} aParent The parent group. If not given the game world will be used instead.
 */
function GameOverCanvas(aGame, aParent) {
	Phaser.Group.call(this, aGame, aParent);

	/* --- pre-init-begin --- */

	// you can insert code here

	/* --- pre-init-end --- */

	this.game.add.sprite(0, 0, 'gameOverBackground', null, this);

	var restartButton = this.game.add.button(448, 896, 'startAtlas', restartGame, this, null, 'restartButton', null, null, this);
	restartButton.anchor.setTo(0.5, 0.5);

	var learnButton = this.game.add.button(1472, 896, 'startAtlas', learn, this, null, 'learnButton', null, null, this);
	learnButton.anchor.setTo(0.5, 0.5);

	 // public fields

	this.fRestartButton = restartButton;
	this.fLearnButton = learnButton;

	/* --- post-init-begin --- */
	
	restartButton.onInputOver.add(buttonScale, {button : this.fRestartButton, scale: 1.25});
	restartButton.onInputOut.add(buttonScale, {button : this.fRestartButton, scale: 1});
	learnButton.onInputOver.add(buttonScale, {button : this.fLearnButton, scale: 1.25});
	learnButton.onInputOut.add(buttonScale, {button : this.fLearnButton, scale: 1});


	/* --- post-init-end --- */
}

/** @type Phaser.Group */
var GameOverCanvas_proto = Object.create(Phaser.Group.prototype);
GameOverCanvas.prototype = GameOverCanvas_proto;
GameOverCanvas.prototype.constructor = Phaser.Group;

/* --- end generated code --- */


/*
 * Starts the game when clicking the start button.
 */
function restartGame() {
	this.game.stats.setStats();
	this.game.state.start("Start");
}

/**
 * button callback that links to a resource on anxiety. Will eventually make page on website to link to,
 * which will have information
 */
function learn() {
	window.open("http://nationalsocialanxietycenter.com/resources/", "_blank");
}

